### ISSUE TITLE
Similarity search stopped working after update

### ISSUE THREAD

**Issue by vityav** [xemle/home-gallery#155] opened 2024-09-21 02:09 UTC
Hello, 
After recently pulling the latest docker versions for the gallery and API after ~6 months of not updating, the similarity search seems to have stopped working. Now whenever I click it on an image's similarity search button, it just takes me back to the timeline view with everything in chronological order.  Depending which picture I start from, the top 4-5 images sometimes shift around, but otherwise everything else (~100k images) remains chronological. Interestingly, the facial recognition similarity still works fine.

There are no errors in the log file or console (both set to debug), but also the API console log doesn't show anything after starting up. I also haven't modified any of the database files since it previously worked. ~~Is this a known issue, and if not, is there a way to ensure the gallery and API are communicating properly?~~ Edit: Rolling back to 1.16.0 gets it working again, but 1.17.0 is broken. I'll step through the commits tomorrow to figure out exactly where it changes.

Thanks!

**Comment by xemle** [comment] 2024-09-22 11:52
Hi @vityav 

I will checked the behavior which you are describing and let you know

**Comment by xemle** [comment] 2024-09-22 14:05
Hi @vityav 

I found the issue. In v1.17.0 I was rewriting the query logic in the browser to support browser query plugins. This introduced a regression which is fixed in the master 1ace064.

Please check if everything is now working as expected.

**Comment by vityav** [comment] 2024-09-22 15:22
That definitely fixed the similarity search problem, thanks for the quick response! 

On the subject of queries, I also can't seem to get location search to work. It seems that by default GPS geolocating populates road, city, and country, but show up in the information sidecar as location, city, and country. Clicking on a location/road will search for "location:roadname" and return 0 results, but manually searching "road:roadname" works. Searching for "exists(location)" will still show everything with locations even though they aren't returned in specific searches. On the demo site they seem to be interchangeable but the demo site also had working similarity search so I assume it's running an older version.

**Comment by xemle** [comment] 2024-09-22 22:07
Hi @vityav you spotted another interesting bug regarding location alias. It should be fixed by 820d967 and the latest master 85e441d. Please review it.

Thank you for the but report!

**Comment by xemle** [comment] 2024-09-22 22:16
> I also found that if you have a large number of tags on one image they could take over the entire width of the screen and squash the image

Should be fixed by 20e6eb8

Anything else? ;-)

**Comment by vityav** [comment] 2024-09-23 05:04
Both working perfectly now, thanks again!

No further issues to report, but I am looking into the plugin system to see if it could handle something like [rclip](https://github.com/yurijmikhalevich/rclip/) as a special query. I feel like it would have to be integrated to keep track of internal paths or at least given some path translation routine,  but could be interesting if I can get it working.

**Comment by xemle** [comment] 2024-09-23 05:18
Perfect!

Regarding Clip and plugin: It is a perfect match and was one of the main intention to open the gallery for more image feature extraction and quering.

Since it is a new feature and the documentation is basic, please do not hesitate to ask questions at dicord or gitter.

Regarding Clip: Many AI models require python, torch, cuda and a Nvidea GPU. Unfortunatley I do not own a Nvidea GPU and would like to use further AI feature extractions. So if you find some interesting CPU only solutions, please let me know. Preferable some docker and REST API solutions, which can be integrated quickly via plugins. One can be used as tutorial documentation how to build such plugin for HomeGallery ;-)

**Comment by xemle** [comment] 2024-09-25 19:07
Requested issue was solved. Closing the issue.

**Closed by xemle** 2024-09-25 19:07 UTC
