### ISSUE TITLE
[practical question] Is there a way to automatically refresh the database when adding images?

### ISSUE THREAD

**Issue by asitemade4u** [xemle/home-gallery#35] opened 2022-05-19 13:27 UTC
Here is the workflow I am currently using, which I find a bit awkward:

1. I add photos to the main directory
2. I open Portainer, change the default shell to `/bin/ash` and go to the Console of the HG stack
3. I execute `/app/gallery.js run import --update` as `root`

Am I missing something? Wouldn't it be more practical to add a refresh button somewhere in the GUI?
NB. I also tried to change the stack `docker-compose.yml` file and add the instruction as an opening `command` but it did not work.

**Comment by xemle** [comment] 2022-05-22 19:39
Currently I do run my gallery on docker compose on an RPI 4 and let the update run per standard cron job and docker-compose command via `docker-compose exec -T gallery /app/gallery.js run import --update`. The used `docker-compose.yml` is from the current [master](https://github.com/xemle/home-gallery/blob/master/docker-compose.yml)

Unfortunately an automatism or UI does not exists yet but is on my top list. The idea would be to define some customized actions in the config to run kind of arbitrary commands such as update. I would also like to define actions to cast the current view to my Chromcast enabled TV, print the current picture to my photo printer or fetch and update from a remote gallery.

Until then my recommendation is to use cron/custom script to do so.

**Comment by tokenwizard** [comment] 2023-01-05 17:46
Could a filewatcher process be used to monitor the source directories and trigger the database update automatically when file changes are detected to those folders?

**Comment by xemle** [comment] 2023-01-05 22:08
@tokenwizard thank you for reaching out.

A file watcher process is not implemented yet and therefore it needs to be implemented/scripted by yourself at the moment. PRs are welcome, too.

I recommend to use a cron script with a good interval matching your desire. Mine is daily cron job. And when I am impatient I execute the import manually.

To understand your desire better: Can you describe your use case?

**Comment by tokenwizard** [comment] 2023-01-06 13:39
I'm using a self-hosted Nextcloud instance that automatically backs up photos I take with my phone. This backup happens frequently, throughout the day, usually within a few minutes of me taking a picture. This makes me assume it is watching the Camera folder for new files and uploading them as it finds one or more. 

I'm running Home Gallery on the same server and sharing the Nextlcoud Uploads folder with it as a source for Photos. It would just be nice if those photos automatically and immediately were indexed into Home Gallery, too. The Nextcloud photo gallery leaves much to be desired. 

I will set up my own filewatcher process, but I thought I would just suggest it here as a possible solution to the OP's question.

**Comment by xemle** [comment] 2023-01-06 22:12
@tokenwizard thank you for the insights.

Great that you are using NextCloud with HomeGallery. It was requested in #31. Would you mind to share your integration in the ticket to help others? How did you bring both worlds together?

Regarding the file watcher request: When the UI supports different customized action like import I will take a watcher into account. Do you have already a feature requirement list like delay option after file change was detected (import after the first change is detected)? Or timer for file change settlements (import after the last change is detected)?

**Comment by tokenwizard** [comment] 2023-01-07 16:46
I added some notes to that other issue/request on my Nextcloud integration.

As for features, I don't really need anything else at the moment. An integrated monitoring process with auto-update of the database would be a killer feature. Aside from that, maybe a way to edit tags from within the picture view itself? 

The current method of clicking Edit, then clicking a bunch of photos, then clicking the other Edit button to add/change tags, then having to click the Reset All button to deselect everything before continuing with the next set of pictures to tag is a bit cumbersome. It certainly works for instances where you are tagging multiple photos with the same tags, but sometimes you are only tagging one at a time, and that is a lot of clicks to add a tag to one photo. 

Actually, that does bring up another topic. I see there was a request for Removing Tags that involves adding a minus sing in front of the tag to remove. It would be much easier if, when viewing an image details, you could just add/remove tags there on that screen.

**Comment by xemle** [comment] 2023-01-07 22:46
> I added some notes to that other issue/request on my Nextcloud integration.

Awesome! Thank you

> As for features, I don't really need anything else at the moment. An integrated monitoring process with auto-update of the database would be a killer feature.

I will take this feature into account. Thank you for this input.

> Aside from that, maybe a way to edit tags from within the picture view itself?

This is requested on #48 and I've updated some interesting news.

**Comment by xemle** [comment] 2023-01-12 06:39
@tokenwizard regarding automatically refresh the database and a file watcher: What do you think about a watch argument on the `gallery.js run import --update --watch` command as first step which runs the import and rerun the import on file changes?

**Comment by tokenwizard** [comment] 2023-01-12 13:33
@xemle  So once you have the database populated initially, you would run that command to trigger it to watch for changes and updated the database automatically? I think that could work. That way if anyone didn't need that functionality, they could just nor include the --watch option.

**Comment by xemle** [comment] 2023-01-13 19:39
@tokenwizard thank you for your feedback.

While the main goal would be to trigger actions from the webapp directly the `--watch` option can be a first iterative solution for an automatically refresh of the database.

**Comment by xemle** [comment] 2023-01-30 15:57
@tokenwizard and @galgofa 

I am currently working on a watch task. The new master was updated and new [docker images](https://hub.docker.com/r/xemle/home-gallery) and [binaries](https://dl.home-gallery.org/dist/unstable/latest/) from current master 5f81592 will be available soon.

```$ ./gallery.js run import --help
gallery.js run import

Import and update new files from sources

Options:
      --version              Show version number                       [boolean]
  -l, --log-level            console log level
         [string] [choices: "trace", "debug", "info", "warn", "error", "silent"]
                                                               [default: "info"]
  -L, --log-file             Log file
      --log-file-level       Log file level
         [string] [choices: "trace", "debug", "info", "warn", "error"] [default:
                                                                        "debug"]
  -c, --config               Configuration file
  -i, --initial              Run initial incremental import            [boolean]
  -u, --update               Check and import new files                [boolean]
  -s, --small-files          Import only small files up to 20MB to exclude big
                             files such as videos to speed up the initial import
                                                                       [boolean]
  -w, --watch                Watch files for changes and run import on changes
                                                                       [boolean]
      --watch-delay          Delay import after file change detection in
                             seconds. A new file change refreshes the previous
                             delay                        [number] [default: 10]
      --watch-max-delay      Maximum delay after file change detection in
                             seconds. Set it to 0 for immediate import on file
                             change                      [number] [default: 600]
      --watch-poll-interval  Use poll interval in seconds. If set 0 watch mode
                             uses fs events if available.  [number] [default: 0]
      --import-on-start      Run import on watch start [boolean] [default: true]
  -h, --help                 Show help                                 [boolean]
```

So a `run import --watch` starts a file watcher and will import the sources on changes. So a periodic call via cronjob is not required anymore. On large media directories or network mounts it is recommended to use `--watch-poll-interval` option. Please do not hesitate to test it and provide feedback.

Further I would like to add `--watch-sources` as option to the server command. Than the sources will always be imported and watched by default. So in a docker container you just need to define your sources and start the container. Everything else will be done automatically. What do you think?

**Comment by xemle** [comment] 2023-01-30 16:10
> Is there an easy way to backup existing metadata/tags so I could blow out the existing instance/container and test this new one, but not need to re-tag everything?

Tags are stored in the [events file](https://docs.home-gallery.org/internals/index.html#id2), so keep this file safe. As long as the media file content does not change the tags will be matched later.

But why start all over it? Just use `run import --watch` by now.

**Comment by tokenwizard** [comment] 2023-01-30 16:17
I would just need to docker-compose pull to get the latest version and then I have that command available?

------- Original Message -------

**Comment by xemle** [comment] 2023-01-30 16:22
I guess you need to run

```
docker-compose pull
docker-compose up
```

**Comment by tokenwizard** [comment] 2023-01-30 16:25
Got it.
Then, to confirm, I would use:
'docker-compose exec gallery run import --watch'

And it should run and automatically watch for new files? I will do this and disable my existing cron task.

------- Original Message -------

**Comment by tokenwizard** [comment] 2023-01-30 16:39
FYI: 
`docker-compose run gallery run import --update --watch`
did actually spawn a new container. I have another folder/container now in /var/lib/docker/containers/

**Comment by xemle** [comment] 2023-01-30 16:46
> Ok, that is running now. Should that automatically background and continue running as a daemon, or do we need to use systemd to keep that running as a background service? I ask because it seems to have completed and I have not been dumped back to my CLI prompt.

Since it is a watch process the job is running in foreground. A daemon option is not jet implemented.

As suggested I would integrate it into the `run server` command as option like `run server --watch-sources` and `run server --no-watch-sources`. 

> If you are going to offer two options for docker-compose, one that does not automatically monitor/refresh and one that does, I would recommend updating the documentation to include the commands to run it each way.

`--watch-sources` will be enabled by default. You would be able to disable it via `GALLERY_WATCH_SOURCES=false` env variable. Do you think this is sufficient?

> Although, I can't imagine anyone using a cloud gallery solution who would not want this feature out of the box.

My use case would be to have it enabled by default. Do you have another use case? Can you describe it?

**Comment by tokenwizard** [comment] 2023-01-30 16:49
Perfect.
I agree the --watch-sources should be enabled by default and running docker-compose up -d would daemonize everything to the background.

I see no reason or use case for anything otherwise.

------- Original Message -------

**Comment by xemle** [comment] 2023-04-22 07:10
The newest master has updates on automatic import. The server now starts the import task with watch option and file changes on source directories will trigger a new import. For docker containers the watcher polls every 5min for compatibility reasons to support slow and network mounts. See the [Dockerfile](https://github.com/xemle/home-gallery/blob/master/Dockerfile) for details.

I want to create a release soon, so please do not hesitate to test it.

**Comment by tokenwizard** [comment] 2023-04-22 12:45
Awesome! I just rebuilt my Nextcloud server so I will throw the docker version on there and give it a go!

**Comment by tokenwizard** [comment] 2023-04-22 13:00
Are there some dependencies I need to install before setting this up? I'm on Debian 11 and I'm getting these errors (several like this) while following along the docker-compose install from the docs. 

![image](https://user-images.githubusercontent.com/24832561/233786289-df42571f-3274-475b-8895-63c0650445f4.png)

**Comment by xemle** [comment] 2023-04-22 14:32
Hi @tokenwizard 

thank you for testing!

Your reported errors are from python and therefore I guess from docker-compose itself. HomeGallery is implemented in JS.

FYI If you have imported your images already an init call is not required. Just start the updated docker compose service.

```
docker-compose pull
docker-compose up -d
```

Maybe watch your logs via

```
docker-compose logs -f gallery
```

As stated above, the default setting in docker is a watch polling interval of 5 min (=300 seconds). Check if it will work with file watcher and set `GALLERY_WATCH_POLL_INTERVAL=0`. Further, when starting the server the import is started automatically and the gallery is looking for new media.

**Comment by tokenwizard** [comment] 2023-04-22 14:39
I think the issue is that Debian 11 uses python 3.9.2 by default and those calls are for functions that have been removed as of around 3.5 (from what my quick research tells me).

What version of Python was this designed for?

**Comment by xemle** [comment] 2023-04-22 16:27
Regarding required python module: I dont know it by heart and would need to search the Internet, too. Maybe an upgrade of docker-compose helps? Further, I think this issue is out of scope for this thread.

**Comment by tokenwizard** [comment] 2023-04-22 16:44
We can close this in favor of taking it elsewhere, but I'm not wure where to post this issue. Does home-gallery use the native python of the host (I'm guessing yes) or does the home-gallery container have it baked in? I have updated docker-compose to the latest version from the Debian 11 repos. 

![image](https://user-images.githubusercontent.com/24832561/233796526-620ae945-aaf9-40d9-a6f3-c21b45e18da6.png)

**Comment by tokenwizard** [comment] 2023-04-22 16:48
SMDH...
I figured it out. I Debian, you have to install BOTH docker-compose and docker.io (not "docker"). In Ubuntu and Arch, installing docker-compose also installs docker. Apparently not in Debian. 

I really do not like Debian, TBH, but the Turnkey Nextcloud appliance is too easy and convenient to pass up.

**Comment by xemle** [comment] 2023-04-22 17:02
> We can close this in favor of taking it elsewhere, but I'm not were where to post this issue

Github provides discussions, HomeGallery uses Gitter/Matrix, PM is also fine

> Does home-gallery use the native python of the host (I'm guessing yes) or does the home-gallery container have it baked in? I have updated docker-compose to the latest version from the Debian 11 repos.

HomeGallery is NodeJs only, no python stuff included. So I am convinced that the python issue is an issue of your host.

But it seams that you figure it out now and you can test the watch function. I am curious if I overeen something or everything works as designed.

**Comment by xemle** [comment] 2023-04-29 06:15
Thank you @EsEnZeT for the hint regarding docker compose plugin. I will update the docs for it. PRs are also welcome which fixes this issue.

**Comment by xemle** [comment] 2023-08-03 17:16
@EsEnZeT the [docker compose](https://docs.home-gallery.org/install/index.html#docker-compose) documentation is updated. 

I am closing this ticket. Feel free to reopen it on any issue.

**Closed by xemle** 2023-08-03 17:16 UTC
