### ISSUE TITLE
Certificate issue？

### ISSUE THREAD

**Issue by Tint0ri** [xemle/home-gallery#50] opened 2022-10-01 15:28 UTC
I installed home-gallery by docker recently. I noticed geo reverse was not working properly. I got error messages from log file like this:
"level":50,"time":1664637422232,"pid":9475,"hostname":"608471ce18d3","module":"extractor.geoReverse","err":{"type":"Error","message":"ETIMEDOUT","stack":"Error: ETIMEDOUT\n    at Timeout.<anonymous> (/app/node_modules/request/request.js:848:19)\n    at listOnTimeout (internal/timers.js:557:17)\n    at processTimers (internal/timers.js:500:7)","code":"ETIMEDOUT","connect":true},"msg":"Could not query geo reverse of 0e558ab *** by URL https://nominatim.openstreetmap.org/reverse?format=jsonv2...
Then I try "wget https://nominatim.openstreetmap.org/reverse?format=jsonv2..." in terminal. I got this:
Resolving nominatim.openstreetmap.org... 184.104.226.109, 2001:470:1:b3b::d
Connecting to nominatim.openstreetmap.org|184.104.226.109|:443... connected.
ERROR: cannot verify nominatim.openstreetmap.org's certificate, issued by ‘CN=R3,O=Let's Encrypt,C=US’:
  Issued certificate has expired.
To connect to nominatim.openstreetmap.org insecurely, use `--no-check-certificate'.

**Comment by xemle** [comment] 2022-10-01 17:07
Hi @Tint0ri 

thank you for using HomeGallery and reporting your issue.

The certificate error is an external issue and HomeGallery can not help here. The error message `certificate has expired` indicates that you might have a system time issue on your side. Maybe your system time is a bit in the future or a lot in the past. Check your local time by the `date` command.

**Comment by Tint0ri** [comment] 2022-10-02 07:39
Thanks for your response. But I'm pretty sure this was not caused by time sync. 
When I try "wget **--no-check-certificate** https://xxxx" in the terminal, it works fine. Cause I'm new bie for Node.js, I did some research and may be this is the solution：
add  one more line in geo-reverse.js at line 67: _rejectUnauthorized: false,_

**Comment by xemle** [comment] 2022-10-02 15:38
> Thanks for your response. But I'm pretty sure this was not caused by time sync. When I try "wget **--no-check-certificate** https://xxxx" in the terminal, it works fine.

If you disable certificates check than you overrule certificate security. This can be valid in known local environment. But this should not be done by default.

So the certificate issue can be caused on the server side but for high traffic services such as the Nominatim service it is very very uncommon and will be fixed within hours. Therefore I guess strongly that the problem is on your side.

My curl/wget tests where fine on my side:

```
$ curl --verbose https://nominatim.openstreetmap.org/reverse?format=jsonv2
*   Trying 130.117.76.9:443...
* Connected to nominatim.openstreetmap.org (130.117.76.9) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*  CAfile: /etc/ssl/certs/ca-certificates.crt
*  CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
* TLSv1.3 (IN), TLS handshake, Finished (20):
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.3 (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384
* ALPN, server accepted to use h2
* Server certificate:
*  subject: CN=dulcy.openstreetmap.org
*  start date: Aug 24 22:06:54 2022 GMT
*  expire date: Nov 22 22:06:53 2022 GMT
*  subjectAltName: host "nominatim.openstreetmap.org" matched cert's "nominatim.openstreetmap.org"
*  issuer: C=US; O=Let's Encrypt; CN=R3
*  SSL certificate verify ok.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x558b5a642cc0)
> GET /reverse?format=jsonv2 HTTP/2
> Host: nominatim.openstreetmap.org
> user-agent: curl/7.74.0
> accept: */*
> 
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* old SSL session ID is stale, removing
* Connection state changed (MAX_CONCURRENT_STREAMS == 128)!
< HTTP/2 400 
< server: nginx
< date: Sun, 02 Oct 2022 15:36:44 GMT
< content-type: application/json; charset=UTF-8
< access-control-allow-origin: *
< access-control-allow-methods: OPTIONS,GET
< 
* Connection #0 to host nominatim.openstreetmap.org left intact
{"error":{"code":400,"message":"Need coordinates or OSM object to lookup."}}
```

> Cause I'm new bie for Node.js, I did some research and may be this is the solution： add one more line in geo-reverse.js at line 67: _rejectUnauthorized: false,_

As I said: Yes it is possible to disable security checks but it is really not recommended. Your reported issue is not an issue of this gallery.

**Closed by xemle** 2022-10-02 15:38 UTC

**Comment by Tint0ri** [comment] 2022-10-10 06:24
Caused by DNS in Dockerfile. Set public dns in docker-compose.yml solved this issue.

**Comment by xemle** [comment] 2022-10-10 06:31
Glad you found the issue
