### ISSUE TITLE
[BUG] Adding filtered-out tag to an image while browsing filtered images results in error.

### ISSUE THREAD

**Issue by Orksork** [xemle/home-gallery#78] opened 2023-04-19 19:36 UTC
If the selection is filtered, by say "not DELETE", and you add the filtered out tag to an image, in this instance "DELETE. After the tag is applied, the page changes to "Unsupported Media Type of".

Nothing breaks besides the workflow, as going back to the filtered selection shows the selection as expected, but it makes it slightly annoying to filter out images to later delete as adding any image to that selection. Ideally, after the filter is re-applied when adding the tag and the image we are currently viewing should be filtered; the app should automatically navigate to the next/previous image in the selection.

**Comment by xemle** [comment] 2023-04-19 21:07
Hi @Orksork 

thank you for reporting this issue.

I can understand that your workflow which you describe can be annoying.

For me this workflow is new and I tag the images on the photo stream and do mostly tagging on multiple images.

The reason why the image is not refreshed has following background: When you copy the URL to share it the app needs to load and the media might not be there immediately. So the current behavior and expectation is that the URL is valid. As example take an image from the demo gallery: [demo.home-gallery.org/view/812444025568](https://demo.home-gallery.org/view/812444025568) It takes a bit of time until the page is loaded and the image is shown.

In your case it is on purpose that the media is not in the selection any more - but it is loaded. So to cover the case of initial loading/waiting and removing from the current select this logic needs to be implemented. PRs are highly welcome.

One other solution could be that the single view has an button on the detail pane to add or remove this image from the selection and you perform the tag action later.

Thanks again to share your thoughts and workflow. Do you have another proposal to solve this issue?

**Comment by xemle** [comment] 2023-04-22 14:39
Hi @Orksork 

after thinking a bit about your report I like your workflow to tag images for deletion. #47 has requested this feature, too.

Would it be an next iteration step to define a special tag for deleted images like `DELETE`. `TRASHED` or `galleryignore` which is automatically filtered by the webapp? So trashed images are not shown. The question for me is how to show the deleted images again if the delete action needs to be undone. Further, should the server already filter the images with a deleted tag, too?

Maybe continue your comment on #47.

**Comment by xemle** [comment] 2023-04-29 06:17
@Orksork this is fixed through c33d70d in the new master build or the newest Docker image. Please retest.

**Comment by xemle** [comment] 2023-08-03 17:19
The issue with "Unsupported Media Type of" is solved.

For the rest: I am closing this as duplicate of https://github.com/xemle/home-gallery/issues/47.

**Closed by xemle** 2023-08-03 17:19 UTC
