### ISSUE TITLE
[improvement] Make it possible to fetch DB from Home-gallery running on different OS

### ISSUE THREAD

**Issue by peter-sc** [xemle/home-gallery#77] opened 2023-04-14 06:54 UTC
Maybe this is just incorrect usage of the fetch command and I didn't get the arguments correctly, but I have found it unable to fetch DB from a native Windows Home-gallery to a docker based Home-gallery.

Use case is following:

First instance of Home-gallery is running on Windows natively, not in docker. When gallery is accessed from Windows, everything works as expected.
The image previews have following path (when viewed in browser):
`<img src="src="files/85\d2\4477714e1a3a371db89a241ea113e7e313fb-image-preview-320.jpg"`

Second Home-gallery instance is running in docker on a Linux host.  The image previews have path:
`<img src="files/91/9e/168c152ca11359743c7d7d298f6279a138fe-image-preview-320.jpg"`

On the second instance, `fetch` command is executed pointing to the first instance. DB is fetched and merged, but the new images are not displayed correctly. The path of the fetched images is in windows-like path style:
`<img src="files/85\d2\4477714e1a3a371db89a241ea113e7e313fb-image-preview-320.jpg"`

On filesystem of second instance, the fetched image is saved with source file-path in windows-style slashes:
`./.cache/home-gallery/storage/85\d2\4477714e1a3a371db89a241ea113e7e313fb-image-preview-320.jpg`

On the second instance, the locally added photos are saved under:
`storage/00/30/bf3952f5464dcf378bcda0726f380f01f7d6-image-preview-320.jpg`

**Comment by xemle** [comment] 2023-04-14 21:38
@peter-sc Thank you very much for this clarification and that issue. To be honest I was not aware that also the image sources of the web app reflect backslashes of the windows path. That should be fixed.

The idea is that the file index, the extractor with its storage cache have platform specific file path separators but the database should have URL format or forward slashes. Then the fetch should be fine between the OSes.

Currently I am working on #35 with automatic import through a file watcher. After that I can handle #74 and this. PRs are also welcome.

**Comment by xemle** [comment] 2023-04-23 06:33
Hi @peter-sc 

The solution seems simpler as expected. Only the preview url path needs to be fixed and the file path format can stay as it is.

My question to you: What is your expectation if you are running the gallery on Windows and Docker: Which file path format would you expect?

Question of host file path separator in the detail view:
![image](https://user-images.githubusercontent.com/261850/233823694-8e78465c-439c-494e-bb66-384afd135eb7.png)

- Should the files reflect the host path separator? So on Windows it is `Camera\IMG_20220503_131533.jpg`
- Should the files path separator be unified? So on Windows and Linux it is `Camera/IMG_20220503_131533.jpg`

Question of file path separator in the detail view after fetching:

- Should the fetch command keep the host path separator? So on a fetch on a Linux machine keeps `Camera\IMG_20220503_131533.jpg` from a Windows machine?
- Should the fetch reflect host path separator? So on a fetch on a Linux machine converts `Camera\IMG_20220503_131533.jpg` from a Windows machine to `Camera/IMG_20220503_131533.jpg`?

**Comment by peter-sc** [comment] 2023-04-23 09:27
Hello @xemle,

When running on Windows in Docker, I suggest the Linux path, as we are running inside Linux in fact.

> File path separator in the detail view after fetching:

Here I'm for:

> 
> * So on a fetch on a Linux machine converts *Camera\IMG_20220503_131533.jpg* from a Windows machine to *Camera/IMG_20220503_131533.jpg*?


* Thank you
* P.

Apr 23, 2023 8:33:36 AM Sebastian ***@***.***>:

**Comment by xemle** [comment] 2023-04-29 06:21
Hi @peter-sc the fetch command was fixed between different OS in cc85758 and is in the current master build and newest Docker images. Please retest.

> * Should the fetch reflect host path separator? So on a fetch on a Linux machine converts Camera\IMG_20220503_131533.jpg from a Windows machine to Camera/IMG_20220503_131533.jpg?

FYI The change does not target the file paths in the UI. Currently I would leave it as it is for the moment. Thank you for your

**Comment by peter-sc** [comment] 2023-05-10 17:03
Hello @xemle,
I have downloaded the binary for windows from master branch, created new configuration pointing to the docker config directory. This was the output after starting it:
```
index.update Index merged of 1491 entries (1488 added, 3 changed, 1539 deleted) 4ms
        A 2023\01\23-01-06 22-10-02 2389.heic
        A 2023\01\23-01-06 22-10-49 2392.heic
        A 2022\12
...
        D 2023/01/23-01-06 22-10-02 2389.heic
        D 2023/01/23-01-06 22-10-49 2392.heic
        D 2022/12
...
```
The gallery is accessible via browser and photos are displayed. Is the index migration from linux to windows paths expected?
The new photos couldn't be added, error message was "Error: Cannot find module 'exiftool-vendored.exe'". The binary from master is just about 76MB, while the stable are about 120 MB. Shall I build the windows binary from source, so that all the dependencies are there?

**Comment by xemle** [comment] 2023-05-11 16:23
> Hello @xemle, I have downloaded the binary for windows from master branch, created new configuration pointing to the docker config directory. This was the output after starting it:
> 
> ```
> index.update Index merged of 1491 entries (1488 added, 3 changed, 1539 deleted) 4ms
>         A 2023\01\23-01-06 22-10-02 2389.heic
>         A 2023\01\23-01-06 22-10-49 2392.heic
>         A 2022\12
> ...
>         D 2023/01/23-01-06 22-10-02 2389.heic
>         D 2023/01/23-01-06 22-10-49 2392.heic
>         D 2022/12
> ...
> ```
> 
> The gallery is accessible via browser and photos are displayed. Is the index migration from linux to windows paths expected? The new photos couldn't be added, error message was "Error: Cannot find module 'exiftool-vendored.exe'". The binary from master is just about 76MB, while the stable are about 120 MB. Shall I build the windows binary from source, so that all the dependencies are there?

You describe the usecase to migrate the files from linux/docker to windows, right? For this the output of the file index looks OK. (The usecase should work in theory but I never testet it. I am mainly working on Linux)

What is not OK is the missing `exiftool-vendored.exe` which is most probably caused by the rewritten binary bundler. I guess I can fix it within the next 2 weeks.

Meanwhile you can try to run it from source. What are the reasons to run the gallery once in Docker and than in Windows? Maybe there are other solutions for the current problem?

**Comment by peter-sc** [comment] 2023-05-11 19:48
I wanted to re-use the generated thumbnails and index files (under Docker) while migrating from Docker to Windows binary, so that the thumbnails don't need to be regenerated again. Didn't realise, that it is a different usecase, as for which the issue was opened, sorry. I can fetch them from the home server. 
Regarding the missing `exiftool-vendored.exe`, I'll wait for your fix and then report status on this issue.

**Comment by xemle** [comment] 2023-05-14 07:23
> I wanted to re-use the generated thumbnails and index files (under Docker) while migrating from Docker to Windows binary, so that the thumbnails don't need to be regenerated again. Didn't realise, that it is a different usecase, as for which the issue was opened, sorry. I can fetch them from the home server.

`fetch` merges a remote gallery into a local one. Only the required files are used, e.g. preview files. The raw data from the extractor step like full exif information are not fetched. Also the file index from remote is not required here.

My usecase for `fetch` is: I have a big NAS with all data. On my Raspery Pi the gallery is fetched from the NAS and requires minimal disk space. This NAS is sometimes on while the pi is always on and serves all files.

Some day there might be the posibility to fetch partial gallery data from friends - kind of federation...

> Regarding the missing `exiftool-vendored.exe`, I'll wait for your fix and then report status on this issue.

The issue with `exiftool-vendored.exe` on windows binary should be fixed in the [latest master](https://dl.home-gallery.org/dist/unstable/latest/)

**Comment by xemle** [comment] 2023-09-30 07:06
Closing it due inactivity. Please do not hesitate to reopen it if required.

**Closed by xemle** 2023-09-30 07:06 UTC
